
SCREEN_WIDTH: int = 640
SCREEN_HEIGHT:int = 480

TYPE_SCREEN_DIMENSIONS = tuple[int, int]
SCREEN_DIMENSIONS: TYPE_SCREEN_DIMENSIONS = (SCREEN_WIDTH, SCREEN_HEIGHT)
# PLAY_OFFSET_HEIGHT = 100
# PLAY_AREA_DIMENSIONS: TYPE_SCREEN_DIMENSIONS = (SCREEN_WIDTH, SCREEN_HEIGHT + PLAY_OFFSET_HEIGHT)