
LINE_WIDTH = 4
CELL_WIDTH = 50


DIRECTION_UP = "up"
DIRECTION_DOWN = "down"
DIRECTION_LEFT = "left"
DIRECTION_RIGHT = "right"

TYPE_DIRECTION = (
    DIRECTION_UP, 
    DIRECTION_DOWN, 
    DIRECTION_LEFT, 
    DIRECTION_RIGHT
) 